---
- name: apt update
  apt:
    update_cache: true
    cache_valid_time: 3600
    force_apt_get: true

- name: Install packages
  package:
    name:
      - less
      - wget
      - curl
      - git
      - unzip
      - htop
      - tmux
      - python3-pip
      - rsync
      - duf
      - bash-completion
    state: present
