---
- name: Create folder
  file:
    path: '/apps/subjectreg/{{ item }}'
    state: directory
  with_items:
    - 'keycloak/import'
    - 'nginx'
    - 'wpf'

- name: Copy files
  copy:
    src: '{{ item }}'
    dest: '/apps/subjectreg'
  with_items:
    - initdb
    - keycloak
  notify: restart subjectreg

- name: Copy templates
  template:
    src: '{{ item.src }}'
    dest: "/apps/subjectreg/{{ item.path | regex_replace('.j2','') }}"
  with_community.general.filetree:
    - 'templates'
  when: item.state == 'file'
  notify: restart subjectreg
